<?php
require_once __DIR__ . '/../includes/portal_layout.php';
require_any_role(['admin', 'secretaria', 'direcao', 'coordenador']);
$user = current_user(); $role = portal_user_role($user);
$q = trim($_GET['q'] ?? ''); $courseId = (int)($_GET['course_id'] ?? 0); $status = trim($_GET['estado'] ?? '');
$courses = portal_rows($pdo, "SELECT id, code, name FROM courses WHERE status='active' ORDER BY name ASC");
$where=[];$params=[];
if($q!==''){ $where[]="(users.full_name LIKE ? OR users.email LIKE ? OR students.student_code LIKE ? OR users.institutional_id LIKE ? OR courses.name LIKE ? OR courses.code LIKE ?)"; $like='%'.$q.'%'; $params=array_merge($params,[$like,$like,$like,$like,$like,$like]); }
if($courseId>0){ $where[]='students.course_id = ?'; $params[]=$courseId; }
if($status!==''){ $where[]='students.enrollment_status = ?'; $params[]=$status; }
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$students=portal_rows($pdo,"SELECT students.*, users.full_name, users.email, users.institutional_id, courses.code AS course_code, courses.name AS course_name, academic_years.name AS academic_year FROM students INNER JOIN users ON users.id=students.user_id LEFT JOIN courses ON courses.id=students.course_id LEFT JOIN academic_years ON academic_years.id=students.academic_year_id {$whereSql} ORDER BY users.full_name ASC LIMIT 250",$params);
portal_layout_start('alunos','Alunos','Consulta de alunos por curso, número de aluno, nome, email e estado.',$role);
?>
<div class="ui-kpi-grid"><div class="ui-kpi is-good"><span>Alunos ativos</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM students WHERE enrollment_status='active'"); ?></strong><small>Matrículas ativas.</small></div><div class="ui-kpi"><span>Total listado</span><strong><?= count($students); ?></strong><small>Resultado do filtro.</small></div><div class="ui-kpi is-info"><span>Cursos com alunos</span><strong><?= portal_count($pdo,"SELECT COUNT(DISTINCT course_id) FROM students"); ?></strong><small>Cursos com matrículas.</small></div><div class="ui-kpi is-warn"><span>Documentos pendentes</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM document_requests WHERE status IN ('pending','in_review')"); ?></strong><small>Pedidos em tratamento.</small></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Lista de alunos</h2><p>Pesquise por número de aluno, nome, email, ID institucional ou curso.</p></div></div><div class="ui-panel-body" style="border-bottom:1px solid var(--ui-divider);"><form method="GET" class="ui-form-grid" style="grid-template-columns:minmax(240px,1fr) 260px 180px auto auto;align-items:end;"><div class="ui-field"><label>Pesquisar</label><input class="ui-control" type="search" name="q" value="<?= e($q); ?>" placeholder="N.º aluno, nome, email ou ID..."></div><div class="ui-field"><label>Curso</label><select class="ui-control" name="course_id"><option value="0">Todos os cursos</option><?php foreach($courses as $c): ?><option value="<?= (int)$c['id']; ?>" <?= $courseId===(int)$c['id']?'selected':''; ?>><?= e(($c['code']??'-').' — '.($c['name']??'-')); ?></option><?php endforeach; ?></select></div><div class="ui-field"><label>Estado</label><select class="ui-control" name="estado"><option value="">Todos</option><option value="active" <?= $status==='active'?'selected':''; ?>>Ativo</option><option value="inactive" <?= $status==='inactive'?'selected':''; ?>>Inativo</option><option value="blocked" <?= $status==='blocked'?'selected':''; ?>>Bloqueado</option></select></div><button class="ui-btn ui-btn-primary">Pesquisar</button><a class="ui-btn ui-btn-ghost" href="<?= e(APP_URL); ?>/pages/alunos.php">Limpar</a></form></div>
<div class="ui-table-wrap"><table class="ui-table"><thead><tr><th>Aluno</th><th>Curso</th><th>Ano letivo</th><th>Estado</th></tr></thead><tbody><?php if(empty($students)): ?><tr><td colspan="4" class="ui-empty">Nenhum aluno encontrado.</td></tr><?php endif; ?><?php foreach($students as $student): ?><tr><td><div class="ui-person"><div class="ui-person-avatar"><?= e(portal_initials_safe($student['full_name']??'')); ?></div><div><strong><?= e($student['full_name']??'-'); ?></strong><small><?= e($student['student_code']??'-'); ?> · <?= e($student['email']??'-'); ?></small></div></div></td><td><strong><?= e($student['course_code']??'-'); ?></strong><small><?= e($student['course_name']??'-'); ?></small></td><td><?= e(($student['academic_year']??'-').' · '.($student['current_year']??'-').'º ano'); ?></td><td><span class="ui-badge <?= e(portal_badge_class($student['enrollment_status']??'')); ?>"><?= e(portal_label_status($student['enrollment_status']??'')); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><?php portal_layout_end(); ?>
