<?php
require_once __DIR__ . '/../includes/portal_layout.php';
require_any_role(['admin','secretaria','direcao','coordenador']);
$user=current_user(); $role=portal_user_role($user); if(user_has_role('secretaria'))$role='secretaria'; if(user_has_role('admin'))$role='admin';
$q=trim($_GET['q']??''); $status=trim($_GET['status']??''); $courseId=(int)($_GET['course_id']??0);
$where=[]; $params=[]; if($q!==''){ $where[]="(applications.full_name LIKE ? OR applications.personal_email LIKE ? OR applications.application_code LIKE ? OR applications.phone LIKE ? OR applications.document_number LIKE ?)"; $like='%'.$q.'%'; $params=array_merge($params,[$like,$like,$like,$like,$like]); }
if($status!==''){ $where[]="applications.status=?"; $params[]=$status; } if($courseId>0){ $where[]="applications.course_id=?"; $params[]=$courseId; }
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$courses=portal_rows($pdo,"SELECT id, code, name FROM courses ORDER BY name ASC");
$apps=portal_rows($pdo,"SELECT applications.*, courses.code AS course_code, courses.name AS course_name FROM applications LEFT JOIN courses ON courses.id=applications.course_id $whereSql ORDER BY applications.created_at DESC LIMIT 200",$params);
$metrics=['total'=>portal_count($pdo,"SELECT COUNT(*) FROM applications"),'pending'=>portal_count($pdo,"SELECT COUNT(*) FROM applications WHERE status IN ('pending','in_review','missing_documents')"),'approved'=>portal_count($pdo,"SELECT COUNT(*) FROM applications WHERE status IN ('documents_validated','approved','credentials_sent')"),'rejected'=>portal_count($pdo,"SELECT COUNT(*) FROM applications WHERE status='rejected'")];
[$success,$error]=portal_flash();
portal_layout_start('candidaturas','Gestão de Candidaturas','Pesquisa, análise e decisão de candidaturas submetidas no portal.',$role);
?>
<?php if($success): ?><div class="ui-alert ui-alert-success"><?= e($success); ?></div><?php endif; ?><?php if($error): ?><div class="ui-alert ui-alert-error"><?= e($error); ?></div><?php endif; ?>
<div class="ui-kpi-grid"><div class="ui-kpi"><span>Total de candidaturas</span><strong><?= (int)$metrics['total']; ?></strong><small>Pedidos submetidos.</small></div><div class="ui-kpi"><span>Por tratar</span><strong><?= (int)$metrics['pending']; ?></strong><small>Pendentes e em análise.</small></div><div class="ui-kpi"><span>Aprovadas</span><strong style="color:var(--ui-success)"><?= (int)$metrics['approved']; ?></strong><small>Validadas ou com credenciais.</small></div><div class="ui-kpi"><span>Rejeitadas</span><strong style="color:var(--ui-danger)"><?= (int)$metrics['rejected']; ?></strong><small>Pedidos recusados.</small></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Candidaturas registadas</h2><p><?= count($apps); ?> resultado(s) encontrado(s)</p></div></div><div class="ui-panel-body" style="border-bottom:1px solid var(--ui-divider)"><form method="GET" class="ui-form-grid" style="grid-template-columns:minmax(260px,1fr) 220px 260px auto"><input class="ui-control" type="search" name="q" value="<?= e($q); ?>" placeholder="Pesquisar por candidato, email, telefone, documento ou código"><select name="status" class="ui-control"><option value="">Todos os estados</option><?php foreach(['pending'=>'Pendente','in_review'=>'Em análise','missing_documents'=>'Documentos em falta','documents_validated'=>'Documentos validados','credentials_sent'=>'Credenciais enviadas','rejected'=>'Rejeitada'] as $k=>$v): ?><option value="<?= e($k); ?>" <?= $status===$k?'selected':''; ?>><?= e($v); ?></option><?php endforeach; ?></select><select name="course_id" class="ui-control"><option value="0">Todos os cursos</option><?php foreach($courses as $c): ?><option value="<?= (int)$c['id']; ?>" <?= $courseId===(int)$c['id']?'selected':''; ?>><?= e(($c['code']??'').' — '.($c['name']??'')); ?></option><?php endforeach; ?></select><div class="ui-actions"><button class="ui-btn ui-btn-secondary" type="submit">Pesquisar</button><a class="ui-btn ui-btn-ghost" href="<?= e(APP_URL); ?>/pages/candidaturas.php">Limpar</a></div></form></div><div class="ui-table-wrap"><table class="ui-table"><thead><tr><th>Candidato</th><th>Curso</th><th>Contacto</th><th>Estado</th><th>Data</th><th>Ações</th></tr></thead><tbody><?php if(empty($apps)): ?><tr><td colspan="6" class="ui-empty">Nenhuma candidatura encontrada.</td></tr><?php endif; ?><?php foreach($apps as $a): ?><tr><td><div class="ui-person"><div class="ui-person-avatar"><?= e(portal_initials_safe($a['full_name']??'')); ?></div><div><strong><?= e($a['full_name']??'-'); ?></strong><small><?= e($a['application_code']??'-'); ?></small><small><?= e($a['personal_email']??'-'); ?></small><small>Doc.: <?= e($a['document_number']??'-'); ?></small></div></div></td><td><strong><?= e($a['course_code']??'-'); ?></strong><small><?= e($a['course_name']??'-'); ?></small></td><td><?= e($a['phone']??'-'); ?></td><td><span class="ui-badge <?= e(portal_badge_class($a['status']??'')); ?>"><?= e(portal_label_status($a['status']??'')); ?></span></td><td><?= e(portal_date($a['created_at']??null)); ?></td><td><a class="ui-btn ui-btn-ghost" href="<?= e(APP_URL); ?>/pages/candidatura_detalhes.php?id=<?= (int)$a['id']; ?>">Detalhes</a></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php portal_layout_end(); ?>
