<?php
require_once __DIR__ . '/../includes/portal_layout.php';
require_any_role(['professor','coordenador','admin']);
$user=current_user(); $uid=(int)$user['id']; $role=portal_user_role($user); $assignmentId=(int)($_GET['assignment_id']??0); [$success,$error]=portal_flash();
$assignments=portal_rows($pdo,"SELECT teacher_subjects.id, subjects.code AS subject_code, subjects.name AS subject_name, academic_classes.name AS class_name FROM teacher_subjects LEFT JOIN subjects ON subjects.id=teacher_subjects.subject_id LEFT JOIN academic_classes ON academic_classes.id=teacher_subjects.class_id WHERE teacher_subjects.teacher_user_id=? AND teacher_subjects.status='active' ORDER BY subjects.name ASC",[$uid]);
$students=[]; if($assignmentId>0){ $students=portal_rows($pdo,"SELECT students.id AS student_id, students.student_code, users.full_name FROM teacher_subjects INNER JOIN class_students ON class_students.class_id=teacher_subjects.class_id INNER JOIN students ON students.id=class_students.student_id INNER JOIN users ON users.id=students.user_id WHERE teacher_subjects.id=? AND teacher_subjects.teacher_user_id=? ORDER BY users.full_name ASC",[$assignmentId,$uid]); }
portal_layout_start('notas','Lançar notas','Registe avaliações por turma, tipo de prova e aluno.',$role==='coordenador'?'coordenador':'professor');
?>
<?php if($success): ?><div class="ui-alert ui-alert-success"><?= e($success); ?></div><?php endif; ?><?php if($error): ?><div class="ui-alert ui-alert-error"><?= e($error); ?></div><?php endif; ?>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Selecionar disciplina</h2><p>Escolha a disciplina/turma antes de lançar avaliações.</p></div></div><div class="ui-panel-body"><div class="ui-actions"><?php if(empty($assignments)): ?><div class="ui-empty">Nenhuma disciplina atribuída ao professor/coordenador.</div><?php endif; ?><?php foreach($assignments as $a): ?><a class="ui-btn <?= $assignmentId===(int)$a['id']?'ui-btn-primary':'ui-btn-ghost'; ?>" href="<?= e(APP_URL); ?>/pages/lancar_notas.php?assignment_id=<?= (int)$a['id']; ?>"><?= e(($a['subject_code']??'-').' · '.($a['class_name']??'-')); ?></a><?php endforeach; ?></div></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Avaliação</h2><p>Defina o tipo de avaliação e preencha as notas dos alunos. Pode repetir o processo para 1.º teste, 2.º teste, trabalho, exame ou recurso.</p></div></div>
<form action="<?= e(APP_URL); ?>/actions/salvar_nota.php" method="POST">
<input type="hidden" name="assignment_id" value="<?= (int)$assignmentId; ?>">
<div class="ui-panel-body" style="border-bottom:1px solid var(--ui-divider);"><div class="ui-form-grid" style="grid-template-columns:240px 1fr 180px 180px;"><div class="ui-field"><label>Tipo</label><select class="ui-control" name="assessment_type"><option value="teste1">1.º teste</option><option value="teste2">2.º teste</option><option value="trabalho">Trabalho</option><option value="frequencia">Frequência</option><option value="exame">Exame</option><option value="recurso">Recurso</option><option value="outro">Outro</option></select></div><div class="ui-field"><label>Nome da avaliação</label><input class="ui-control" name="assessment_label" placeholder="Ex.: Trabalho prático 1, Teste intermédio..."></div><div class="ui-field"><label>Data</label><input class="ui-control" type="text" name="assessment_date_visible" placeholder="dd/mm/aaaa" maxlength="10"></div><div class="ui-field"><label>Estado</label><select class="ui-control" name="status"><option value="draft">Rascunho</option><option value="submitted">Submetido</option></select></div></div></div>
<div class="ui-table-wrap"><table class="ui-table"><thead><tr><th>Aluno</th><th>Nota</th><th>Observação</th></tr></thead><tbody><?php if($assignmentId<=0): ?><tr><td colspan="3" class="ui-empty">Escolha uma disciplina.</td></tr><?php elseif(empty($students)): ?><tr><td colspan="3" class="ui-empty">Sem alunos nesta turma.</td></tr><?php endif; ?><?php foreach($students as $s): ?><tr><td><strong><?= e($s['full_name']); ?></strong><small><?= e($s['student_code']); ?></small></td><td style="max-width:160px;"><input class="ui-control" type="number" step="0.01" min="0" max="20" name="grade_value[<?= (int)$s['student_id']; ?>]" placeholder="0-20"></td><td><input class="ui-control" name="notes[<?= (int)$s['student_id']; ?>]" placeholder="Observação opcional"></td></tr><?php endforeach; ?></tbody></table></div>
<?php if($assignmentId>0 && !empty($students)): ?><div class="ui-panel-body"><button class="ui-btn ui-btn-primary" type="submit">Guardar notas da turma</button></div><?php endif; ?>
</form></div>
<script>(function(){var i=document.querySelector('input[name="assessment_date_visible"]'); if(i){i.addEventListener('input',function(){var v=i.value.replace(/\D/g,'').slice(0,8); i.value=v.length>=5?v.slice(0,2)+'/'+v.slice(2,4)+'/'+v.slice(4):v.length>=3?v.slice(0,2)+'/'+v.slice(2):v;});}})();</script>
<?php portal_layout_end(); ?>
