<?php
require_once __DIR__ . '/../includes/portal_layout.php'; require_any_role(['aluno','admin']); $user=current_user(); $student=portal_one($pdo,"SELECT * FROM students WHERE user_id=? LIMIT 1",[(int)$user['id']]); $sid=(int)($student['id']??0);
$rows=portal_rows($pdo,"SELECT payments.*, fees.title, fees.month_reference, fees.amount_cve AS fee_amount FROM payments LEFT JOIN fees ON fees.id=payments.fee_id WHERE payments.student_id=? ORDER BY payments.created_at DESC",[$sid]); [$success,$error]=portal_flash();
portal_layout_start('pagamentos','Propinas','Pagamentos, comprovativos e estado de validação.','aluno');
?>
<?php if($success): ?><div class="ui-alert ui-alert-success"><?= e($success); ?></div><?php endif; ?><?php if($error): ?><div class="ui-alert ui-alert-error"><?= e($error); ?></div><?php endif; ?>
<div class="ui-kpi-grid"><div class="ui-kpi"><span>Total</span><strong><?= count($rows); ?></strong><small>Propinas registadas.</small></div><div class="ui-kpi"><span>Em análise</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM payments WHERE student_id=? AND status='em_analise'",[$sid]); ?></strong><small>Comprovativos enviados.</small></div><div class="ui-kpi"><span>Confirmados</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM payments WHERE student_id=? AND status='confirmado'",[$sid]); ?></strong><small>Pagamentos validados.</small></div><div class="ui-kpi"><span>Valor confirmado</span><strong style="font-size:26px"><?= e(portal_money(portal_count($pdo,"SELECT COALESCE(SUM(amount_cve),0) FROM payments WHERE student_id=? AND status='confirmado'",[$sid]))); ?></strong><small>Total validado.</small></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Minhas propinas</h2><p>Envie comprovativo quando necessário.</p></div></div><div class="ui-panel-body"><div class="ui-card-list"><?php if(empty($rows)): ?><div class="ui-empty">Sem pagamentos registados.</div><?php endif; ?><?php foreach($rows as $p): ?><div class="ui-card-row"><div class="ui-split"><div><h3><?= e(($p['title']??'Propina').' — '.($p['month_reference']??'')); ?></h3><p style="color:var(--ui-muted)">Valor: <strong><?= e(portal_money($p['amount_cve']??$p['fee_amount']??0)); ?></strong></p><span class="ui-badge <?= e(portal_badge_class($p['status']??'')); ?>"><?= e(portal_label_status($p['status']??'')); ?></span><?php if(!empty($p['proof_file'])): ?><p><a class="ui-btn ui-btn-ghost" target="_blank" href="<?= e(APP_URL.'/'.ltrim($p['proof_file'],'/')); ?>">Ver comprovativo</a></p><?php endif; ?></div><form action="<?= e(APP_URL); ?>/actions/enviar_comprovativo.php" method="POST" enctype="multipart/form-data" style="display:grid;gap:12px"><input type="hidden" name="payment_id" value="<?= (int)$p['id']; ?>"><div class="ui-field"><label>Comprovativo</label><input class="ui-control" type="file" name="proof_file" accept=".pdf,.jpg,.jpeg,.png"></div><button class="ui-btn ui-btn-primary" type="submit">Enviar comprovativo</button></form></div></div><?php endforeach; ?></div></div></div>
<?php portal_layout_end(); ?>
