<?php
require_once __DIR__ . '/../includes/portal_layout.php';
require_any_role(['professor','coordenador','admin']);
$user=current_user(); $uid=(int)$user['id']; $role=portal_user_role($user); $assignmentId=(int)($_GET['assignment_id']??0); $classDate=$_GET['class_date']??date('Y-m-d'); [$success,$error]=portal_flash();
$assignments=portal_rows($pdo,"SELECT teacher_subjects.id, subjects.code AS subject_code, subjects.name AS subject_name, academic_classes.name AS class_name FROM teacher_subjects LEFT JOIN subjects ON subjects.id=teacher_subjects.subject_id LEFT JOIN academic_classes ON academic_classes.id=teacher_subjects.class_id WHERE teacher_subjects.teacher_user_id=? AND teacher_subjects.status='active' ORDER BY subjects.name ASC",[$uid]);
$students=[]; if($assignmentId>0){ $students=portal_rows($pdo,"SELECT students.id AS student_id, students.student_code, users.full_name FROM teacher_subjects INNER JOIN class_students ON class_students.class_id=teacher_subjects.class_id INNER JOIN students ON students.id=class_students.student_id INNER JOIN users ON users.id=students.user_id WHERE teacher_subjects.id=? AND teacher_subjects.teacher_user_id=? ORDER BY users.full_name ASC",[$assignmentId,$uid]); }
portal_layout_start('faltas','Registar faltas','Marque presenças, faltas ou justificações por turma e data.',$role==='coordenador'?'coordenador':'professor');
?>
<?php if($success): ?><div class="ui-alert ui-alert-success"><?= e($success); ?></div><?php endif; ?><?php if($error): ?><div class="ui-alert ui-alert-error"><?= e($error); ?></div><?php endif; ?>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Selecionar disciplina e data</h2><p>Escolha a turma e a data da aula para carregar a pauta de presenças.</p></div></div><div class="ui-panel-body"><form method="GET" class="ui-form-grid" style="grid-template-columns:1fr 220px auto"><select name="assignment_id" class="ui-control"><?php foreach($assignments as $a): ?><option value="<?= (int)$a['id']; ?>" <?= $assignmentId===(int)$a['id']?'selected':''; ?>><?= e(($a['subject_code']??'-').' · '.($a['class_name']??'-')); ?></option><?php endforeach; ?></select><input class="ui-control" type="date" name="class_date" value="<?= e($classDate); ?>"><button class="ui-btn ui-btn-primary">Carregar</button></form></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Pauta da aula</h2><p>Por defeito, os alunos ficam como presentes. Marque falta ou justificada quando necessário.</p></div></div><form action="<?= e(APP_URL); ?>/actions/salvar_falta.php" method="POST"><input type="hidden" name="assignment_id" value="<?= (int)$assignmentId; ?>"><input type="hidden" name="class_date" value="<?= e($classDate); ?>"><div class="ui-table-wrap"><table class="ui-table"><thead><tr><th>Aluno</th><th>Presente</th><th>Falta</th><th>Justificada</th><th>Observação</th></tr></thead><tbody><?php if($assignmentId<=0): ?><tr><td colspan="5" class="ui-empty">Escolha uma disciplina.</td></tr><?php elseif(empty($students)): ?><tr><td colspan="5" class="ui-empty">Sem alunos nesta turma.</td></tr><?php endif; ?><?php foreach($students as $s): ?><tr><td><strong><?= e($s['full_name']); ?></strong><small><?= e($s['student_code']); ?></small></td><td><label><input type="radio" name="status[<?= (int)$s['student_id']; ?>]" value="present" checked> Presente</label></td><td><label><input type="radio" name="status[<?= (int)$s['student_id']; ?>]" value="absent"> Falta</label></td><td><label><input type="radio" name="status[<?= (int)$s['student_id']; ?>]" value="justified"> Justificada</label></td><td><input class="ui-control" name="notes[<?= (int)$s['student_id']; ?>]" placeholder="Observação opcional"></td></tr><?php endforeach; ?></tbody></table></div><?php if($assignmentId>0 && !empty($students)): ?><div class="ui-panel-body"><button class="ui-btn ui-btn-primary" type="submit">Guardar presenças da turma</button></div><?php endif; ?></form></div><?php portal_layout_end(); ?>
