<?php
require_once __DIR__ . '/../includes/portal_layout.php';
require_any_role(['funcionario', 'admin', 'secretaria']);
$user=current_user(); $role=portal_user_role($user);
portal_layout_start('tarefas','Tarefas','Fila operacional de apoio académico e administrativo.',$role);
?>
<div class="ui-kpi-grid"><div class="ui-kpi is-warn"><span>Documentos</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM document_requests WHERE status IN ('pending','in_review')"); ?></strong><small>Pedidos por tratar.</small></div><div class="ui-kpi is-info"><span>Pagamentos</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM payments WHERE status='em_analise'"); ?></strong><small>Comprovativos em análise.</small></div><div class="ui-kpi"><span>Candidaturas</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM applications WHERE status IN ('pending','in_review','missing_documents')"); ?></strong><small>Processos por acompanhar.</small></div><div class="ui-kpi is-good"><span>Hoje</span><strong><?= portal_count($pdo,"SELECT COUNT(*) FROM activity_logs WHERE DATE(created_at)=CURDATE()"); ?></strong><small>Atividades registadas.</small></div></div>
<div class="ui-panel"><div class="ui-panel-header"><div><h2>Atalhos operacionais</h2><p>O funcionário apoia tarefas administrativas específicas. A aprovação final continua com a secretaria, coordenação ou direção, conforme o processo.</p></div></div><div class="ui-panel-body"><div class="ui-grid-3"><a class="ui-card-row" style="grid-template-columns:1fr;text-decoration:none;color:inherit;" href="<?= e(APP_URL); ?>/pages/validar_documentos.php"><strong>Preparar documentos</strong><span style="color:var(--ui-muted);">Apoiar emissão, anexar ficheiros e encaminhar pedidos para validação.</span></a><a class="ui-card-row" style="grid-template-columns:1fr;text-decoration:none;color:inherit;" href="<?= e(APP_URL); ?>/pages/validar_pagamentos.php"><strong>Apoiar pagamentos</strong><span style="color:var(--ui-muted);">Consultar comprovativos e sinalizar pendências para a secretaria.</span></a><a class="ui-card-row" style="grid-template-columns:1fr;text-decoration:none;color:inherit;" href="<?= e(APP_URL); ?>/pages/gerir_horarios.php"><strong>Apoiar horários</strong><span style="color:var(--ui-muted);">Registar horários definidos pela coordenação e secretaria.</span></a></div></div></div>
<?php portal_layout_end(); ?>
